name: doclense
description: An Indian made Open source PDF creator Android app
publish_to: "none"

version: 1.0.1+2

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  animated_splash_screen: ^1.3.0
  camera: ^0.10.4
  double_back_to_close_app: ^2.1.0
  easy_folder_picker: ^1.3.0
  flutter_launcher_icons: ^0.11.0
  flutter_spinkit: ^5.1.0
  flutter_svg: ^2.0.5
  fluttertoast: ^8.2.1
  gallery_saver: ^2.3.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  image_cropper: ^3.0.3
  image_picker: ^0.8.7+4
  intl: ^0.18.0
  introduction_screen: ^3.1.8
  open_file: ^3.3.1
  package_info_plus: ^3.1.2
  path: ^1.8.2
  path_provider: ^2.0.14
  pdf: ^3.8.4
  pdf_viewer_plugin: ^2.0.1
  permission_handler: ^10.2.0
  photofilters: ^3.0.1
  printing: ^5.9.3
  provider: ^6.0.5
  quick_actions: ^1.0.2
  rating_dialog: ^2.0.4
  # share: ^2.0.4
  share_plus: ^6.3.4
  shared_preferences: ^2.1.0
  source_span: ^1.10.0
  url_launcher: ^6.1.10
  wiredash: ^1.7.0

dev_dependencies:
  build_runner: ^2.3.2
  # flutter_test:
  #   sdk: flutter
  hive_generator: ^2.0.0
lint: ^1.10.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/app_icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/
    - assets/aboutPage/
    - assets/images/team/
