name: doclense
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  animated_splash_screen: ^1.0.1+2
  camera: ^0.5.8+5
  cupertino_icons: ^0.1.3
  double_back_to_close_app: ^2.0.1
  esys_flutter_share: ^1.0.2
  ext_storage: ^1.0.3
  flutter_full_pdf_viewer: ^1.0.6
  flutter_share: ^1.0.5
  flutter_svg: ^0.19.3
  fluttertoast: ^8.0.3
  folder_picker: ^0.3.0
  gallery_saver: null
  hive: ^1.4.4+1
  hive_flutter: ^0.3.1
  image_cropper: ^1.3.1
  image_picker: ^0.6.7+21
  intl: ^0.15.7
  introduction_screen: ^1.0.9
  open_file: ^2.0.3
  package_info: ^2.0.0
  path: ^1.7.0
  path_provider: ^1.6.27
  pdf: ^1.9.0
  pdf_viewer_plugin: ^1.1.1
  permission: ^0.1.7
  permission_handler: null
  photofilters: ^2.0.1
  provider: ^4.3.3
  quick_actions: ^0.4.0+10
  rating_dialog: ^1.0.0
  share: ^0.6.5+4
  shared_preferences: ^0.5.12+4
  source_span: ^1.7.0
  storage_path: ^0.2.0
  url_launcher: ^5.7.10
  wiredash: ^0.5.0
  flutter_launcher_icons: ^0.7.2+1
  flutter_spinkit: ^5.0.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: null
  hive_generator: ^0.8.2
  lint: ^1.0.0

flutter_icons:    
 android: true    
 ios: true    
 image_path: "assets/app_icon.png"  

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  assets:
    - assets/images/
    - assets/
    - assets/aboutPage/
    - assets/images/team/
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
dependencies_overrides:
  collection: ^1.14.12
